### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by GnuriaN** [r3nya/cv#1]
```E:\!Git!\cv>C:\"Program Files (x86)\Yarn\bin\yarn.cmd" install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > muicss@0.9.20" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
[4/4] Building fresh packages...
Done in 87.50s.

E:\!Git!\cv>C:\"Program Files (x86)\Yarn\bin\yarn.cmd" run open
yarn run v1.15.2
$ gulp open
[23:39:39] Requiring external module babel-register
[23:39:40] Using gulpfile E:\!Git!\cv\gulpfile.babel.js
[23:39:40] Starting 'open'...
[23:39:40] 'open' errored after 146 ms
[23:39:40] Error: File not found with singular glob: E:\!Git!\cv\dest\index.html
    at Glob.<anonymous> (E:\!Git!\cv\node_modules\glob-stream\index.js:41:11)
    at Object.onceWrapper (events.js:277:13)
    at Glob.emit (events.js:189:13)
    at Glob.EventEmitter.emit (domain.js:441:20)
    at Glob._finish (E:\!Git!\cv\node_modules\glob\glob.js:172:8)
    at done (E:\!Git!\cv\node_modules\glob\glob.js:159:12)
    at Glob._processSimple2 (E:\!Git!\cv\node_modules\glob\glob.js:652:12)
    at E:\!Git!\cv\node_modules\glob\glob.js:640:10
    at Glob._stat2 (E:\!Git!\cv\node_modules\glob\glob.js:736:12)
    at lstatcb_ (E:\!Git!\cv\node_modules\glob\glob.js:728:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by GnuriaN** [comment]
I did not build the project because this was not said :-(

**Comment by r3nya** [comment]
@r3nya it's just my CV. 🤷‍♂

**Comment by r3nya** [comment]
http://r3nya.ru/cv/ btw :)
